name: Publish package
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
       global-json-file: global.json
       cache: true
       cache-dependency-path: src/**/packages.lock.json
    - run: dotnet restore --locked-mode
    - run: dotnet pack --no-restore --include-symbols -o . /p:Version=${GITHUB_REF_NAME}

  deploy:
    runs-on: ubuntu-latest
    needs: pack
    steps:
      - name: Deploy to NuGet
        run: dotnet nuget push *.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

      - name: Deploy to GitHub Package Registry
        run: dotnet nuget push *.nupkg --api-key $NUGET_AUTH_TOKEN --source https://nuget.pkg.github.com/anexia/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

