name: "Run tests"

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
       global-json-file: global.json
       cache: true
       cache-dependency-path: src/**/packages.lock.json
    - run: dotnet restore --locked-mode
    - run: dotnet test
