name: "Run tests"

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
       global-json-file: global.json
       cache: true
       cache-dependency-path: src/**/packages.lock.json
    - run: dotnet restore --locked-mode
    - name: Run tests with coverage
      run: dotnet test --no-restore /p:CollectCoverage=true --logger trx --results-directory "test-results"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        comment_mode: off
        files: |
          test-results/**/*.xml
          test-results/**/*.trx
          test-results/**/*.json
