name: "Run tests"

on: [ push, pull_request ]


jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
       global-json-file: global.json
       cache: true
    - run: dotnet restore --locked-mode
    - run: dotnet test
